modLoader = "javafml"
loaderVersion = "${fml_version_constraint}"
issueTrackerURL = "https://github.com/quinn-semele/expanded-storage/issues"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${nf_authors}"
logoFile = "icon.png"
displayURL = "https://modrinth.com/mod/expanded-storage"
description = "${description}"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${nf_minecraft_constraint}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_id}-common.mixins.json"

[[mixins]]
config = "${mod_id}-neoforge.mixins.json"
