modLoader = "javafml"
loaderVersion = "${fml_version_constraint}"
license = "${license}"
issueTrackerURL = "${issue_tracker}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${nf_authors}"
displayURL = "${homepage}"
logoFile = "icon.png"
description = "${description}"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${nf_minecraft_constraint}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_id}-common.mixins.json"

[[mixins]]
config = "${mod_id}-neoforge.mixins.json"
